kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-sensor-simulator
  namespace: devconf-demo
  labels:
    app: iot-sensor-simulator
    kind: sensors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-simulator
  template:
    metadata:
      labels:
        app: iot-sensor-simulator
        kind: sensors
    spec:
      containers:
        - name: iot-sensor-simulator
          image: >-
            quay.io/kubealex/iot-sensor-simulator:latest
          envFrom:
            - configMapRef:
                name: sensor-simulator-config
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
