---
- name: Devconf-demo | Acknowledge anomaly
  hosts: localhost
  tasks:
    - name: Devconf-demo | Print event data
      ansible.builtin.debug:
        msg:
          - "Sensor location: {{ ansible_eda.event.sensor_location }}"
          - "Sensor ID: {{ ansible_eda.event.sensor_id }}"
          - "Sensor event type: {{ ansible_eda.event.sensor_event_type }}"
          - "Sensor temperature delta: {{ ansible_eda.event.sensor_temperature_delta }}"

    - name: Check info
      kubernetes.core.k8s_info:
        kubeconfig: "/eda-ansible/kubeconfig"
        kind: ConfigMap
        name: "{{ item }}"
        namespace: devconf-demo
        validate_certs: false
      register: cm_out
      loop:
        - iot-sensor-internal
        - iot-sensor-floor
        - iot-sensor-fridge

    - name: Set sensor settings as facts
      ansible.builtin.set_fact:
        sensor_internal: "{{ cm_out.results.0.resources.0 }}"
        sensor_floor: "{{ cm_out.results.1.resources.0 }}"
        sensor_fridge: "{{ cm_out.results.2.resources.0 }}"

    - name: Set sensors values as facts
      ansible.builtin.set_fact:
        sensor_internal_temperature: "{{ sensor_internal.data['sensor.fixed-temperature'] }}"
        sensor_internal_humidity: "{{ sensor_internal.data['sensor.humidity'] }}"
        sensor_floor_temperature: "{{ sensor_floor.data['sensor.fixed-temperature'] }}"
        sensor_floor_humidity: "{{ sensor_floor.data['sensor.humidity'] }}"
        sensor_fridge_fan_speed: "{{ sensor_fridge.data['sensor.fan-speed'] }}"
        sensor_fridge_eco_mode: "{{ sensor_fridge.data['sensor.eco-mode'] }}"
        sensor_fridge_fixed_temperature: "{{ sensor_fridge.data['sensor.fixed-temperature'] }}"
        sensor_fridge_power_consumption: "{{ sensor_fridge.data['sensor.power-consumption'] }}"

    - name: React to temperature changes
      kubernetes.core.k8s_json_patch:
        kubeconfig: "/eda-ansible/kubeconfig"
        kind: ConfigMap
        namespace: devconf-demo
        name: "{{ item.sensor_name }}"
        validate_certs: false
        patch:
          - op: replace
            path: /data/sensor.fixed-temperature
            value: "{{ item.sensor_fixed_temperature }}"
          - op: replace
            path: /data/sensor.fan-speed
            value: "{{ item.sensor_fan_speed }}"
          - op: replace
            path: /data/sensor.power-consumption
            value: "{{ item.sensor_power_consumption }}"
          - op: replace
            path: /data/sensor.eco-mode
            value: "{{ item.sensor_eco_mode }}"
      loop:
        - sensor_name: iot-sensor-fridge
          sensor_fixed_temperature: "{{ sensor_fridge_fixed_temperature | int - (ansible_eda.event.sensor_temperature_delta | int) }}"
          sensor_power_consumption: "{{ sensor_fridge_power_consumption | int + (ansible_eda.event.sensor_temperature_delta | int * 100) }}"
          sensor_fan_speed: "{{ sensor_fridge_fan_speed | int + (ansible_eda.event.sensor_temperature_delta | int * 100) }}"
          sensor_eco_mode: "{{ 'false' if (sensor_fridge_fixed_temperature | int - (ansible_eda.event.sensor_temperature_delta | int)) | int < -8 else 'true' }}"

    - name: Restart sensor
      kubernetes.core.k8s:
        kubeconfig: "/eda-ansible/kubeconfig"
        kind: Pod
        namespace: devconf-demo
        validate_certs: false
        label_selectors:
          - app=iot-sensor-fridge
        state: absent
