kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-eda
  namespace: devconf-demo
  labels:
    app: iot-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-eda
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iot-eda
    spec:
      containers:
        - name: iot-eda
          image: >-
            quay.io/kubealex/iot-eda:latest
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccount: eda-admin
      serviceAccountName: eda-admin
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
