kind: Deployment
apiVersion: apps/v1
metadata:
  name: influxdb
  namespace: devconf-demo
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
        deployment: influxdb
    spec:
      volumes:
        - name: influxdb-cache
          persistentVolumeClaim:
            claimName: influxdb-cache
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-storage
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: influxdb
          envFrom:
            - secretRef:
                name: influxdb-init
          ports:
            - containerPort: 8086
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: influxdb-cache
              mountPath: /etc/influxdb2
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2
          terminationMessagePolicy: File
          image: >-
            docker.io/library/influxdb:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
