bases:
  - ../base
patches:
  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: iot-sensor-fridge
    target:
      kind: Deployment
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/metadata/labels/app"
        value: iot-sensor-fridge
    target:
      kind: Deployment
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: iot-sensor-fridge
    target:
      kind: Deployment
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: iot-sensor-fridge
    target:
      kind: Deployment
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: iot-sensor-fridge
    target:
      kind: Service
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/spec/selector/app"
        value: iot-sensor-fridge
    target:
      kind: Service
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/metadata/labels/app"
        value: iot-sensor-fridge
    target:
      kind: Service
      name: iot-sensor-simulator

  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/envFrom/0/configMapRef/name"
        value: iot-sensor-fridge
    target:
      kind: Deployment
      name: iot-sensor-simulator

configMapGenerator:
  - name: iot-sensor-fridge
    namespace: devconf-demo
    literals:
      - sensor.location=fridge-room-c1-fridge
      - sensor.device-id=fridge-01
      - sensor.fan-speed=150
      - sensor.eco-mode=true
      - sensor.fixed-temperature=-8
      - sensor.power-consumption=200
generatorOptions:
  disableNameSuffixHash: true
