FROM registry.access.redhat.com/ubi9-minimal
RUN microdnf install java-17 python3 gcc python3-devel -y && microdnf clean all && python -m ensurepip --upgrade && pip3 install ansible ansible-rulebook asyncio aiokafka aiohttp aiosignal asyncio_mqtt kubernetes
ENV JAVA_HOME="/usr/lib/jvm/jre-17"
RUN mkdir /eda-ansible
COPY playbooks /eda-ansible/playbooks
COPY kubeconfig inventory rulebook.yml /eda-ansible
RUN ls -lat /eda-ansible
RUN ansible-galaxy collection install ansible.eda kubealex.eda
WORKDIR /eda-ansible
USER root
CMD ansible-rulebook -i inventory --rulebook rulebook.yml --verbose
