---
- name: Wait for sensor events
  hosts: all
  sources:
    - kubealex.eda.mqtt:
        host: mosquitto
        port: 1883
        topic: anomaly-data-out
  rules:
    - name: Resolve anomaly
      condition: event.sensor_location is defined
      action:
        run_playbook:
          name: playbooks/acknowledge_anomaly.yml
