---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: iot-admin
  namespace: devconf-demo
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iot-admin
  namespace: devconf-demo
subjects:
  - kind: ServiceAccount
    name: iot-admin
    namespace: devconf-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: eda-admin
  namespace: devconf-demo
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-admin
  namespace: devconf-demo
subjects:
  - kind: ServiceAccount
    name: eda-admin
    namespace: devconf-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
