kind: Deployment
apiVersion: apps/v1
metadata:
  name: mosquitto
  namespace: devconf-demo
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mosquitto
        deployment: mosquitto
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: mosquitto-1
          emptyDir: {}
        - name: mosquitto-2
          emptyDir: {}
        - name: config-volume
          configMap:
            name: mosquitto-config
      containers:
        - name: mosquitto
          image: >-
            docker.io/library/eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: mosquitto-1
              mountPath: /mosquitto/data
            - name: mosquitto-2
              mountPath: /mosquitto/log
            - name: config-volume
              mountPath: /mosquitto/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
