kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-sensor-aggregator
  namespace: devconf-demo
  labels:
    app: iot-sensor-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-aggregator
  template:
    metadata:
      labels:
        app: iot-sensor-aggregator
        deployment: iot-sensor-aggregator
    spec:
      containers:
        - name: iot-sensor-aggregator
          image: >-
            quay.io/kubealex/iot-sensor-aggregator:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: iot-admin
      serviceAccount: iot-admin
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
